### ISSUE TITLE
complete.cases

### ISSUE THREAD

**Issue by daniel1noble** [fontikar/egerniasl#1]
Commit f3b888a you use complete cases. Be careful here as it will exclude all NA latency as well. You don't want that. This would apply to all *.process.R files when doing initial exclusion. You want to only exclude NA where no data exists for trial

**Comment by fontikar** [comment]
Hey Dan, I used complete.cases for a the column "Correct" i.e. if lizard didn't attempt task, she would have received an NA, and I excluded this type of data. NA in latency is still there in the generated dataset.

**Comment by daniel1noble** [comment]
Aha. OK. Cool. I see that now. All good!
